Traceback (most recent call last):
  File "./src/pygtk_posting.py", line 98, in listen_postgres
    self.db.poll()
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

Traceback (most recent call last):
  File "/media/reuben/nas/pygtk_posting-0.3.1/src/unpaid_invoices.py", line 140, in focus
    self.treeview_populate()
  File "/media/reuben/nas/pygtk_posting-0.3.1/src/unpaid_invoices.py", line 157, in treeview_populate
    self.cursor.execute("SELECT i.id, i.name, amount_due, c.name, c.id, "
psycopg2.InterfaceError: cursor already closed
Traceback (most recent call last):
  File "./src/pygtk_posting.py", line 584, in destroy
    self.cursor.execute("UNLISTEN products")
psycopg2.InterfaceError: cursor already closed
